[package]
name = "cozymuseum-critterarium"
version = "3.0.3"
description = "CozyMuseum Critterarium desktop host"
authors = ["CozyMuseum"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
